# Generated by Django 5.1.6 on 2025-03-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_desc',
            field=models.CharField(default='Vanakkam', max_length=200),
            preserve_default=False,
        ),
    ]
